/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Oraclep;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eparrales
 */
public class Cliente extends javax.swing.JFrame {
      DefaultTableModel modta2;
    Oraclep ora2;
     
    /**
     * Creates new form VentanaCliente
     */
    public Cliente() {
        initComponents();
        modta2 = new DefaultTableModel();
        ora2= new Oraclep();
        modJtxt();

        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreContactoLabel = new javax.swing.JLabel();
        dniField = new javax.swing.JTextField();
        nombresField = new javax.swing.JTextField();
        telFijoField = new javax.swing.JTextField();
        dniLabel = new javax.swing.JLabel();
        telCelularField = new javax.swing.JTextField();
        nombresLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        telFijoLabel = new javax.swing.JLabel();
        ciudadField = new javax.swing.JTextField();
        telCelularLabel = new javax.swing.JLabel();
        direccionField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        nombreContactoField = new javax.swing.JTextField();
        ciudadLabel = new javax.swing.JLabel();
        direccionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaclient = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        btnNuevoRegistro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbcodigo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");

        nombreContactoLabel.setText("Nombre Contacto:");

        dniField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dniFieldMouseClicked(evt);
            }
        });

        dniLabel.setText("Dni:");

        nombresLabel.setText("Nombres:");

        telFijoLabel.setText("Tel Fijo:");

        telCelularLabel.setText("Tel Celular:");

        emailLabel.setText("Email:");

        ciudadLabel.setText("Ciudad:");

        direccionLabel.setText("Direccion:");

        tablaclient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaclient.setSelectionBackground(new java.awt.Color(255, 255, 51));
        tablaclient.setSelectionForeground(new java.awt.Color(0, 0, 255));
        tablaclient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaclientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaclient);

        btnActualizar.setText("Refresh");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        saveButton.setText("Guardar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        btnNuevoRegistro.setText("Nuevo");
        btnNuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoRegistroActionPerformed(evt);
            }
        });

        jLabel1.setText("CLIENTES");

        jLabel2.setText("Codigo:");

        lbcodigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Dni:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevoRegistro)
                                .addGap(34, 34, 34)
                                .addComponent(saveButton)
                                .addGap(33, 33, 33)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btneliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dniLabel)
                                    .addComponent(nombresLabel)
                                    .addComponent(telFijoLabel)
                                    .addComponent(telCelularLabel)
                                    .addComponent(emailLabel)
                                    .addComponent(ciudadLabel)
                                    .addComponent(direccionLabel)
                                    .addComponent(nombreContactoLabel)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dniField)
                                    .addComponent(nombresField)
                                    .addComponent(telFijoField)
                                    .addComponent(telCelularField)
                                    .addComponent(emailField)
                                    .addComponent(ciudadField)
                                    .addComponent(direccionField)
                                    .addComponent(nombreContactoField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(58, 58, 58)
                        .addComponent(btnActualizar)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnBuscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(jLabel3)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(lbcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniLabel)
                    .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombresLabel)
                    .addComponent(nombresField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telFijoLabel)
                    .addComponent(telFijoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telCelularLabel)
                    .addComponent(telCelularField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciudadLabel)
                    .addComponent(ciudadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionLabel)
                    .addComponent(direccionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreContactoLabel)
                    .addComponent(nombreContactoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoRegistro)
                    .addComponent(btneliminar)
                    .addComponent(saveButton)
                    .addComponent(btnModificar)
                    .addComponent(btnActualizar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        refresh();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        String dnip = dniField.getText();
        int respuesta = JOptionPane.showConfirmDialog(null, " ¿Esta seguro que desea elminiar el registro? " +dnip, "Eliminar Registro", JOptionPane.YES_NO_CANCEL_OPTION);
        switch (respuesta) {
            case JOptionPane.YES_OPTION:
            System.out.println("" + respuesta);
            break;
            case JOptionPane.NO_OPTION:

            break;
            case JOptionPane.CANCEL_OPTION:

            break;
        }

        if (respuesta == 0) {

            try {

                CallableStatement cs1 = ora2.getCon().getConexion().prepareCall("call p_elimclient(?)");
                cs1.setString(1,dnip);
                cs1.execute();

            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int codp = Integer.parseInt(lbcodigo.getText());
        String dni,nombres,telfijo,telcel,email,ciudad ,direccion,nombrecont,sql;
        dni = dniField.getText();
        nombres = nombresField.getText();
        telfijo= telFijoField.getText();
        telcel = telCelularField.getText();
        email = emailField.getText();
        ciudad  = ciudadField.getText();
        direccion= direccionField.getText();
        nombrecont= nombreContactoField.getText();
        try {

            CallableStatement cs = ora2.getCon().getConexion().prepareCall("call mod_client(?,?,?,?,?,?,?,?,?)");
            cs.setInt(1,codp);
            cs.setString(2,dni);
            cs.setString(3,nombres);
            cs.setString(4,telfijo);
            cs.setString(5,telcel);
            cs.setString(6,email);
            cs.setString(7,ciudad);
            cs.setString(8,direccion);
            cs.setString(9,nombrecont);
            cs.execute();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // Metodo para insertar los datos en la tabla especialistas
        String dni,nombres,telfijo,telcel,email,ciudad ,direccion,nombrecont,sql;
        
        dni = dniField.getText();
        nombres = nombresField.getText();
        telfijo= telFijoField.getText();
        telcel = telCelularField.getText();
        email = emailField.getText();
        ciudad  = ciudadField.getText();
        direccion= direccionField.getText();
        nombrecont= nombreContactoField.getText();
        sql="insert into clientes values(null,'"+dni+"','"+nombres+"','"+telfijo+"','"+telcel+"','"+email+"','"+ciudad+"','"+direccion+"','"+nombrecont+"')";
        ora2.regisData(sql);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void btnNuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoRegistroActionPerformed
        // Limpiar los campos para ingresar un registro nuevo

        limpCampos();
    }//GEN-LAST:event_btnNuevoRegistroActionPerformed

    private void tablaclientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaclientMouseClicked
        // TODO add your handling code here:
         int fila = tablaclient.getSelectedRow();
        lbcodigo.setText(tablaclient.getModel().getValueAt(fila, 0).toString());
       
        dniField.setText(tablaclient.getModel().getValueAt(fila, 1).toString());
        nombresField.setText(tablaclient.getModel().getValueAt(fila, 2).toString());
        telFijoField.setText(tablaclient.getModel().getValueAt(fila, 3).toString());
        telCelularField.setText(tablaclient.getModel().getValueAt(fila, 4).toString());
        emailField.setText(tablaclient.getModel().getValueAt(fila, 5).toString());
        ciudadField.setText(tablaclient.getModel().getValueAt(fila, 6).toString());
        direccionField.setText(tablaclient.getModel().getValueAt(fila, 7).toString());
        nombreContactoField.setText(tablaclient.getModel().getValueAt(fila, 8).toString());
        
        
        
        
        
        
        
    }//GEN-LAST:event_tablaclientMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // Realizar busqueda de registros en la tabla especialisatas

        String dnipp = txtbuscar.getText();
       
        modta2 = new DefaultTableModel();
         
        ora2.consultar("select * from clientes where dni='"+dnipp+"'");

        try {
            int numCol = ora2.getRstmdata().getColumnCount();
            for (int i = 0; i < numCol; i++) {
                modta2.addColumn(ora2.getRstmdata().getColumnLabel(i + 1));

            }

            while (ora2.getRst().next()) {
                Object[] fila = new Object[numCol];
                for (int i = 0; i < numCol; i++) {
                    fila[i] = ora2.getRst().getObject(i + 1);
                }

                modta2.addRow(fila);
                tablaclient.setModel(modta2);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void dniFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dniFieldMouseClicked
       try{ 
        Orden.idClientesField.setText(dniField.getText());
       }catch(Exception e){
           
       }
        
    }//GEN-LAST:event_dniFieldMouseClicked

     // metodos utilitarios
    
     public void refresh(){
          modta2= new DefaultTableModel();
          String sql="select * from clientes";
          ora2.consultar(sql);
           
         try {
             int numCol = ora2.getRstmdata().getColumnCount();
             for (int i = 0; i < numCol; i++) {
                 modta2.addColumn(ora2.getRstmdata().getColumnLabel(i + 1));

             }

             while (ora2.getRst().next()) {
                 Object[] fila = new Object[numCol];
                 for (int i = 0; i < numCol; i++) {
                     fila[i] = ora2.getRst().getObject(i + 1);
                 }

                 modta2.addRow(fila);
                 tablaclient.setModel(modta2);
             }

         } catch (Exception e) {
         }
    }
   
    public void limpCampos() {
        dniField.setText("");
        nombresField.setText("");
        telFijoField.setText("");
        telCelularField.setText("");
        emailField.setText("");
        ciudadField.setText("");
        direccionField.setText("");
        nombreContactoField.setText("");
        lbcodigo.setText("");
                

    }
    
    public void soloNum(JTextField tx) {
        tx.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isLetter(c)) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });
    }
    public void soloCaract(JTextField tx) {
        tx.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isDigit(c)) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });

    }
    
    public void modJtxt(){
        soloNum(telFijoField);
        soloNum(telCelularField);
        soloCaract(nombresField);
        soloCaract(ciudadField);
      
        
        
    }
    

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevoRegistro;
    private javax.swing.JButton btneliminar;
    private javax.swing.JTextField ciudadField;
    private javax.swing.JLabel ciudadLabel;
    private javax.swing.JTextField direccionField;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JTextField dniField;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbcodigo;
    private javax.swing.JTextField nombreContactoField;
    private javax.swing.JLabel nombreContactoLabel;
    private javax.swing.JTextField nombresField;
    private javax.swing.JLabel nombresLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTable tablaclient;
    private javax.swing.JTextField telCelularField;
    private javax.swing.JLabel telCelularLabel;
    private javax.swing.JTextField telFijoField;
    private javax.swing.JLabel telFijoLabel;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
