/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Oraclep;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eparrales
 */
public class Proveedores extends javax.swing.JFrame {
    DefaultTableModel modta2;
    Oraclep ora2;
    

    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
        modta2 = new DefaultTableModel();
        ora2= new Oraclep();
        modJtxt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        nombreContactoLabel = new javax.swing.JLabel();
        ciudadLabel = new javax.swing.JLabel();
        direccionLabel = new javax.swing.JLabel();
        nitField = new javax.swing.JTextField();
        nombreField = new javax.swing.JTextField();
        telFijoField = new javax.swing.JTextField();
        nitLabel = new javax.swing.JLabel();
        telCelularField = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        telFijoLabel = new javax.swing.JLabel();
        nombreContactoField = new javax.swing.JTextField();
        telCelularLabel = new javax.swing.JLabel();
        ciudadField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        direccionField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProvee = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lbcod = new javax.swing.JLabel();
        btnNuevoRegistro = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtbusnit = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnasignarpro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Proveedores E&S.");

        jLabel9.setText("REGISTRO DE PROVEEDORES ");

        nombreContactoLabel.setText("Nombre Contacto:");

        ciudadLabel.setText("Ciudad:");

        direccionLabel.setText("Direccion:");

        nitLabel.setText("Nit:");

        nombreLabel.setText("Nombre:");

        telFijoLabel.setText("Tel Fijo:");

        telCelularLabel.setText("Tel Celular:");

        emailLabel.setText("Email:");

        tablaProvee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProvee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProveeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProvee);

        jLabel1.setText("Codigo:");

        lbcod.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNuevoRegistro.setText("Nuevo");
        btnNuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoRegistroActionPerformed(evt);
            }
        });

        saveButton.setText("Guardar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Refresh");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nit:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnasignarpro.setText("Asignar Proveedor");
        btnasignarpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnasignarproActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevoRegistro)
                                .addGap(34, 34, 34)
                                .addComponent(saveButton)
                                .addGap(33, 33, 33)
                                .addComponent(btnModificar)
                                .addGap(18, 18, 18)
                                .addComponent(btneliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnActualizar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nitLabel)
                                    .addComponent(nombreLabel)
                                    .addComponent(telFijoLabel)
                                    .addComponent(telCelularLabel)
                                    .addComponent(emailLabel)
                                    .addComponent(nombreContactoLabel)
                                    .addComponent(ciudadLabel)
                                    .addComponent(direccionLabel)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtbusnit, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(btnBuscar)
                                        .addGap(113, 113, 113))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(ciudadField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                            .addComponent(nombreContactoField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(telCelularField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(telFijoField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nombreField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nitField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(direccionField)
                                            .addComponent(lbcod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnasignarpro))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(jLabel2)
                    .addComponent(txtbusnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbcod, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nitLabel)
                    .addComponent(btnasignarpro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telFijoLabel)
                    .addComponent(telFijoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telCelularLabel)
                    .addComponent(telCelularField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreContactoLabel)
                    .addComponent(nombreContactoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciudadLabel)
                    .addComponent(ciudadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionLabel)
                    .addComponent(direccionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoRegistro)
                    .addComponent(btneliminar)
                    .addComponent(saveButton)
                    .addComponent(btnModificar)
                    .addComponent(btnActualizar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoRegistroActionPerformed
        // Limpiar los campos para ingresar un registro nuevo

        limpCampos();

    }//GEN-LAST:event_btnNuevoRegistroActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // Metodo para insertar los datos en la tabla especialistas
        String nit,nom,telfijo,telcel,email,ciudad,dire,nomcon,sql;
        nit=nitField.getText();
        nom=nombreField.getText();
        
        telfijo=telFijoField.getText();
        telcel=telCelularField.getText();
        email=emailField.getText();
        nomcon=nombreContactoField.getText();
        ciudad=ciudadField.getText();
        dire=direccionField.getText();
        sql="insert into proveedores values(null,'"+nit+"','"+nom+"','"+telfijo+"','"+telcel+"','"+email+"','"+nomcon+"','"+ciudad+"','"+dire+"')";
        ora2.regisData(sql);

    }//GEN-LAST:event_saveButtonActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int codp = Integer.parseInt(lbcod.getText());
        String nit,nom,telfijo,telcel,email,ciudad,dire,nomcon,sql;
        nit=nitField.getText();
        nom=nombreField.getText();
        
        telfijo=telFijoField.getText();
        telcel=telCelularField.getText();
        email=emailField.getText();
        nomcon=nombreContactoField.getText();
        ciudad=ciudadField.getText();
        dire=direccionField.getText();
        try {

            CallableStatement cs = ora2.getCon().getConexion().prepareCall("call p_modprovee(?,?,?,?,?,?,?,?,?)");
            cs.setInt(1,codp);
            cs.setString(2,nit);
            cs.setString(3,nom);
            cs.setString(4,telfijo);
            cs.setString(5,telcel);
            cs.setString(6,email);
            cs.setString(7,nomcon);
            cs.setString(8,ciudad);
            cs.setString(9,dire);
            cs.execute();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        String nitp = nitField.getText();
        int respuesta = JOptionPane.showConfirmDialog(null, " ¿Esta seguro que desea elminiar el registro? " + nitp, "Eliminar Registro", JOptionPane.YES_NO_CANCEL_OPTION);
        switch (respuesta) {
            case JOptionPane.YES_OPTION:
                System.out.println("" + respuesta);
                break;
            case JOptionPane.NO_OPTION:

                break;
            case JOptionPane.CANCEL_OPTION:

                break;
        }

        if (respuesta == 0) {

            try {

                CallableStatement cs1 = ora2.getCon().getConexion().prepareCall("call p_elimprovee(?)");
                cs1.setString(1,nitp);
                cs1.execute();

            } catch (Exception e) {
            }

        }

    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        refresh();

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tablaProveeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProveeMouseClicked
    int fila = tablaProvee.getSelectedRow();
        lbcod.setText(tablaProvee.getModel().getValueAt(fila, 0).toString());
        nitField.setText(tablaProvee.getModel().getValueAt(fila, 1).toString());
        nombreField.setText(tablaProvee.getModel().getValueAt(fila, 2).toString());
        telFijoField.setText(tablaProvee.getModel().getValueAt(fila, 3).toString());
        telCelularField.setText(tablaProvee.getModel().getValueAt(fila, 4).toString());
        emailField.setText(tablaProvee.getModel().getValueAt(fila, 5).toString());
        nombreContactoField.setText(tablaProvee.getModel().getValueAt(fila, 6).toString());
        ciudadField.setText(tablaProvee.getModel().getValueAt(fila, 7).toString());
        direccionField.setText(tablaProvee.getModel().getValueAt(fila, 8).toString());

       
        
        
    }//GEN-LAST:event_tablaProveeMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // Realizar busqueda de registros en la tabla especialisatas

        String nitp= txtbusnit.getText();
        modta2 = new DefaultTableModel();

        ora2.consultar("select * from proveedores  where nit='"+nitp+"'");

        try {
            int numCol = ora2.getRstmdata().getColumnCount();
            for (int i = 0; i < numCol; i++) {
                modta2.addColumn(ora2.getRstmdata().getColumnLabel(i + 1));

            }

            while (ora2.getRst().next()) {
                Object[] fila = new Object[numCol];
                for (int i = 0; i < numCol; i++) {
                    fila[i] = ora2.getRst().getObject(i + 1);
                }

                modta2.addRow(fila);
                tablaProvee.setModel(modta2);
            }

        } catch (Exception e) {
        }finally{
            if(modta2.getRowCount()==0){
                JOptionPane.showMessageDialog(null," El registro "+nitp+" no se encuenrar ");
            }
            
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnasignarproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnasignarproActionPerformed
        try {
            Inventarios.txtprovee.setText(nitField.getText());
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, " Debe ingresar un nit de proveedor ");
        }

    }//GEN-LAST:event_btnasignarproActionPerformed

    
    
    
    
    
    
    // metodos utilitarios
    
     public void refresh(){
          modta2= new DefaultTableModel();
          String sql="select * from proveedores";
          ora2.consultar(sql);
           
         try {
             int numCol = ora2.getRstmdata().getColumnCount();
             for (int i = 0; i < numCol; i++) {
                 modta2.addColumn(ora2.getRstmdata().getColumnLabel(i + 1));

             }

             while (ora2.getRst().next()) {
                 Object[] fila = new Object[numCol];
                 for (int i = 0; i < numCol; i++) {
                     fila[i] = ora2.getRst().getObject(i + 1);
                 }

                 modta2.addRow(fila);
                 tablaProvee.setModel(modta2);
             }

         } catch (Exception e) {
         }
    }
   
    public void limpCampos() {
        lbcod.setText("");
        nitField.setText("");
        nombreField.setText("");
        telFijoField.setText("");
        telCelularField.setText("");
        emailField.setText("");
        nombreContactoField.setText("");
        direccionField.setText("");
        direccionField.setText("");
        ciudadField.setText("");
        txtbusnit.setText("");

    }
    
    public void soloNum(JTextField tx) {
        tx.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isLetter(c)) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });
    }
    public void soloCaract(JTextField tx) {
        tx.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isDigit(c)) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });

    }
    
    public void modJtxt(){
        soloNum(telFijoField);
        soloNum(telCelularField);
        soloCaract(nombreField);
        soloCaract(ciudadField);
      
        
        
    }
    
    
    
    
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevoRegistro;
    private javax.swing.JButton btnasignarpro;
    private javax.swing.JButton btneliminar;
    private javax.swing.JTextField ciudadField;
    private javax.swing.JLabel ciudadLabel;
    private javax.swing.JTextField direccionField;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbcod;
    private javax.swing.JTextField nitField;
    private javax.swing.JLabel nitLabel;
    private javax.swing.JTextField nombreContactoField;
    private javax.swing.JLabel nombreContactoLabel;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTable tablaProvee;
    private javax.swing.JTextField telCelularField;
    private javax.swing.JLabel telCelularLabel;
    private javax.swing.JTextField telFijoField;
    private javax.swing.JLabel telFijoLabel;
    private javax.swing.JTextField txtbusnit;
    // End of variables declaration//GEN-END:variables
}
